# Generated by Django 4.1.5 on 2023-07-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomno', models.IntegerField()),
                ('rows', models.IntegerField()),
                ('columns', models.IntegerField()),
                ('noofbenches', models.IntegerField()),
                ('benchstrength', models.IntegerField()),
            ],
        ),
    ]
